language: python
dist: focal
python:
    - "3.9"
    - "3.8"
    - "3.7"
    - "3.6"
install: pip install -r dev-requirements.txt
script:
    - "flake8 tepet"
    - "pylint tepet"
    - "mypy tepet"
    - "coverage erase"
    - "coverage run --include=tepet/* -m pytest -ra"
    - "coverage report -m"
